name: ssh remote commands

on: 
#   push:
#     branches:
#       - master
  # pull_request:
  workflow_dispatch:
  
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: SCP Files
          uses: appleboy/scp-action@v0.0.1
          with:
              host: ec2-54-206-118-148.ap-southeast-2.compute.amazonaws.com
              key: ${{ secrets.KEY }}
              username: ubuntu
              port: 22
              source: "./nix-init.sh"
              target: "/home/ubuntu"

        - name: SSH Remote Commands
          uses: appleboy/ssh-action@v0.1.4
          with:
              host: ec2-54-206-118-148.ap-southeast-2.compute.amazonaws.com
              key: ${{ secrets.KEY }}
              username: ubuntu
              port: 22
              script: |
                  sudo curl https://nixos.org/releases/nix/nix-2.7.0/install | sh
                  sudo bash nix-init.sh
