name: terraform deploy

on: 
#   push:
#     branches:
#       - master
  # pull_request:
  workflow_dispatch:
  
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      
      - name: Terraform Initiallise
        id: init
        run: terraform init
        
      - name: Terraform Validate
        id: validate
        run: terraform validate
      
      - name: Terraform Apply
        run: terraform apply -auto-approve
      
      - name: Store Public ip 
        id: ipV4adrr
        run: |
            ipAddress=$(terraform output | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' )
            echo "::set-output name=publicIP::$ipAddress"
            
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
            host: ${{steps.ipV4adrr.outputs.publicIP}}
            username: ubuntu
            key: ${{ secrets.KEY }}
            port: 22
            source: "nix-init.sh"
            target: "/home/ubuntu"
        
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
              host: ${{steps.ipV4adrr.outputs.publicIP}}
              key: ${{ secrets.KEY }}
              username: ubuntu
              port: 22
              script: |
                  sudo curl https://nixos.org/releases/nix/nix-2.7.0/install | sh
                  sudo bash nix-init.sh
